### PR TITLE
guidelines version 0.7

### PR DESCRIPTION
**Pull request by emunozh**
Updated guidelines pdf

### CODE REVIEW

**Comment by mlauster** [comment]
@emunozh, this branch has conflicts. Can you please merge `cstb:master` into `emunozh:master` and resolve conflicts?

**Comment by emunozh** [comment]
Done!

**Comment by mlauster** [comment]
I don't know what changes so fast in files concerning the pdf creation, but we have conflicts again. @emunozh,  can you please merge cstb:master into emunozh:master and resolve conflicts again?

**Comment by mlauster** [comment]
@emunozh , is this ready for merge or do you still plan to add something?

**Comment by emunozh** [comment]
The brach is ready for merge on cstb/citygml-energy/master

**Pull request merged**
